# Generated by Django 6.0.6 on 2026-07-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_email_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_service_account',
            field=models.BooleanField(default=False),
        ),
    ]
